version: '3.7'

services:
  minio1:
    image: minio/minio
    volumes:
      - /mnt/minio1/data1:/data1
      - /mnt/minio1/data2:/data2
      - /home/ghost/.minio/minio1:/root/.minio
    ports:
      - "9001:443"
    environment:
      MINIO_ACCESS_KEY: AKIAIOSFODNN7EXAMPLE
      MINIO_SECRET_KEY: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    command: server --address ":443" https://minio{1...4}/data{1...2} 
    healthcheck:
      test: ["CMD", "curl", "-fk", "https://localhost:443/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio2:
    image: minio/minio
    volumes:
      - /mnt/minio2/data1:/data1
      - /mnt/minio2/data2:/data2
      - /home/ghost/.minio/minio2:/root/.minio
    ports:
      - "9002:443"
    environment:
      MINIO_ACCESS_KEY: AKIAIOSFODNN7EXAMPLE
      MINIO_SECRET_KEY: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    command: server --address ":443" https://minio{1...4}/data{1...2}
    healthcheck:
      test: ["CMD", "curl", "-fk", "https://localhost:443/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio3:
    image: minio/minio
    volumes:
      - /mnt/minio3/data1:/data1
      - /mnt/minio3/data2:/data2
      - /home/ghost/.minio/minio3:/root/.minio
    ports:
      - "9003:443"
    environment:
      MINIO_ACCESS_KEY: AKIAIOSFODNN7EXAMPLE
      MINIO_SECRET_KEY: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    command: server --address ":443" https://minio{1...4}/data{1...2} 
    healthcheck:
      test: ["CMD", "curl", "-fk", "https://localhost:443/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio4:
    image: minio/minio
    volumes:
      - /mnt/minio4/data1:/data1
      - /mnt/minio4/data2:/data2
      - /home/ghost/.minio/minio4:/root/.minio
    ports:
      - "9004:443"
    environment:
      MINIO_ACCESS_KEY: AKIAIOSFODNN7EXAMPLE
      MINIO_SECRET_KEY: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    command: server --address ":443" https://minio{1...4}/data{1...2}
    healthcheck:
      test: ["CMD", "curl", "-fk", "https://localhost:443/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
