---
version: "2.2"

services:
  node1:
    image: openio.node1
    container_name: uvs.node1
    hostname: node1
    networks:
      sds_openio:
        ipv4_address: 172.28.0.2
    ports:
      - "6007:6007"
    volumes:
       - "~/contener-data/node1:/mnt"
    #  - "/sys/fs/cgroup:/sys/fs/cgroup"
    privileged: true
    command: /usr/lib/systemd/systemd

  node2:
    image: openio.node2
    container_name: uvs.node2
    hostname: node2
    networks:
      sds_openio:
        ipv4_address: 172.28.0.3
    volumes:
       - "~/contener-data/node2:/mnt"
    #  - "/sys/fs/cgroup:/sys/fs/cgroup"
    privileged: true

  node3:
    image: openio.node3
    container_name: uvs.node3
    hostname: node3
    networks:
      sds_openio:
        ipv4_address: 172.28.0.4
    volumes:
       - "~/contener-data/node3:/mnt"
    #  - "/sys/fs/cgroup:/sys/fs/cgroup"
    privileged: true
    command: /usr/lib/systemd/systemd

networks:
  sds_openio:
    external: true
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
...

      
